### ISSUE TITLE
Import issue with last scipy verions

### ISSUE THREAD

**Issue by GamelinAl** [lnls-fac/collective_effects#28]
Hi,

Do you know that the code do not work with the last versions of scipy (>=1.14) ?
Is there any reason to keep simps instead of simpson ? Or can it be changed without breaking things for you ?

```
>>> import pycolleff
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dockeruser/collective_effects/pycolleff/pycolleff/__init__.py", line 7, in <module>
    from . import longitudinal_equilibrium
  File "/home/dockeruser/collective_effects/pycolleff/pycolleff/longitudinal_equilibrium.py", line 10, in <module>
    from scipy.integrate import quad as _quad, simps as _simps
ImportError: cannot import name 'simps' from 'scipy.integrate' (/home/dockeruser/miniconda3/lib/python3.11/site-packages/scipy/integrate/__init__.py)
>>> import scipy
>>> scipy.__version__
'1.14.1'
```

**Comment by murilobalves** [comment]
Hello Alexis, thanks for pointing out the issue.

Yes I just notice this problem when running the script you shared in the mbtrack2 conda environment with newer scipy version. 
This could be fixed in this PR https://github.com/lnls-fac/collective_effects/pull/29 that is already merged into master branch.

Thank you.
